<?php
/**
 * @category    Herve
 * @package     Herve_TopLinks
 * @copyright   Copyright (c) 2013 Hervé Guétin (http://www.herveguetin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<li>
    <div class="block">
        <div class="block-content">
            <p class="block-subtitle"><?php echo $this->__('Our products are the best ever!')?></p>
        </div>
    </div>
</li>